########### Azure Disk demo-1 should be created into the same Azure Availability Zone where node lies and onto which pvc can be mounted on the pod ########
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: pv-azuredisk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce    ### PersistentVolume resources that are backed by azure disks don't support ReadWriteMany.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/51XXXXX6-af44-XXX-9a24-XXXXXX17915d/resourcegroups/aks-noderg/providers/microsoft.compute/disks/demo-1
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce   ### ReadWriteOnce accessModes indicates volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-01
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: mycontainer-01
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: myvol
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: pvc-azuredisk
